"use client";

import type { Metadata } from 'next';
// import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import Header from '@/app/ui/layout/header';
import Footer from '@/app/ui/layout/footer';
import '@radix-ui/themes/styles.css';
import { Theme } from '@radix-ui/themes';
import { ThemeProvider } from 'next-themes';
import { WagmiProvider } from 'wagmi';
import { config } from '@/web3/config';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { GeistSans } from 'geist/font/sans';
import { GeistMono } from 'geist/font/mono';

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// };

// ⚠️ 注意: 必须在组件外部创建 QueryClient 实例，避免在组件内引起死循环
const queryClient = new QueryClient();

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${GeistSans.variable} ${GeistMono.variable} antialiased flex flex-col min-h-screen`}
      >
        {/* wagmi 全局上下文注入 */}
        <WagmiProvider config={config}>
          {/* react-query全局上下文注入 */}
          <QueryClientProvider client={queryClient}>
          <ThemeProvider>
            <Theme className="flex flex-1 flex-col">
              <Header />
              <div className="flex-1">{children}</div>
              <Footer />
            </Theme>
          </ThemeProvider>
          </QueryClientProvider>
        </WagmiProvider>
      </body>
    </html>
  );
}
